version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: chioma_db
    restart: always
    environment:
      POSTGRES_USER: postgres_cax
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chioma_db
    ports:
      - '5432:5432'
    volumes:
      - chioma_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chioma_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  chioma_postgres_data:
